%YAML:1.0
---
                            ####Surface Measurement parameters######
#Paramid image
num_level: 3
#Bilateral Filter, see OpenCV website
#Filter size: Large filters (d > 5) are very slow, so it is recommended to use d=5 for real-time applications, and perhaps d=9 for offline applications that need heavy noise filtering.
kernel_size: 5
#Filter sigma in the color space. A larger value of the parameter means that farther colors within the pixel neighborhood (see sigmaSpace ) will be mixed together, resulting in larger areas of semi-equal color
sigma_color: 1
#Filter sigma in the coordinate space. A larger value of the parameter means that farther pixels will influence each other as long as their colors are close enough (see sigmaColor ). When d>0 , it specifies the neighborhood size regardless of sigmaSpace . Otherwise, d is proportional to sigmaSpace .
sigma_space: 1
                                #####TSDF Volume parameters #######
#Volume resolution of TSDF volume, it defines how many voxels in 3 dimensions x,y,z
volume_resolution: 512
#Voxel size (in meters), the size of each voxel
voxel_size: 0.001
#The initial distance of the camera from the volume center along the x,y,z-axis (in meters)
original_distance_x: -0.2
original_distance_y: -0.2
original_distance_z: 0
#The truncation distance for both updating and raycasting the TSDF volume, it should be equal to voxel_size * 5
truncation_distance: 0.005
#Depth distance cut off, if it is too far away from camera
depth_cutoff: 5.0
#The maximum buffer size for exporting pointclouds; adjust if run out of memory when exporting
pointcloud_buffer_size: 6000000
# The maximum buffer size for exporting pointclouds; adjust if run out of memory when exporting
mesh_buffer_size: 6000000
#Max distance for ICP
maxDistance: 0.007
# ICP configuration
# The distance threshold (as described in the paper) in meters
distance_threshold: 0.01
# The angle threshold (as described in the paper) in degrees
angle_threshold: 20.0
# Number of ICP iterations for each level from original level 0 to highest scaled level (sparse to coarse)
icp_iterations: [ 4, 5, 10 ]
                                ####Learning Station parameters######
#Parameter for the 3D BoundingBox of the learning station to remove outside points
BoundingBox:
 mixX: 0.03 
 maxX: 0.3
 minY: 0.03
 maxY: 0.25
 minZ: 0.009
 maxZ: 0.4
#Perform plane equalization if 1, else 0 if no
plane_equalized: 1
#Number of views if the station moves step by step
nCapture: 36
#Set up the speed of the learning station, the maximum speed = 14 
speed: 14
#Set up the learning station moving step by step or continiously moving
#Step by step :1 Continiously move 0
mode: 0
#If mesh = 1, it will perform kinectfusion
mesh: 1
# Perform Euclidean Clustering, only fuse clusters of points with more than threshold
threshold_cluster: 2500
###Debugging
# Show and save images, clouds, etc for debugging
debug: 1
#Perform Moving Least Square, set search radius
mls: 0.01




